2023-05-22 15:59:54,876 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Configure stats pid to 60614
2023-05-22 15:59:54,876 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Loading settings from /home/marco/.config/wandb/settings
2023-05-22 15:59:54,876 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Loading settings from /home/marco/Documents/graph_3d_generation/wandb/settings
2023-05-22 15:59:54,876 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-05-22 15:59:54,876 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-22 15:59:54,876 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Applying login settings: {'anonymous': 'must'}
2023-05-22 15:59:54,877 INFO    MainThread:60614 [wandb_init.py:_log_setup():476] Logging user logs to /home/marco/Documents/graph_3d_generation/wandb/run-20230522_155954-3d6riaq0/logs/debug.log
2023-05-22 15:59:54,877 INFO    MainThread:60614 [wandb_init.py:_log_setup():477] Logging internal logs to /home/marco/Documents/graph_3d_generation/wandb/run-20230522_155954-3d6riaq0/logs/debug-internal.log
2023-05-22 15:59:54,877 INFO    MainThread:60614 [wandb_init.py:_jupyter_setup():426] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f0ca3caa890>
2023-05-22 15:59:54,878 INFO    MainThread:60614 [wandb_init.py:init():516] calling init triggers
2023-05-22 15:59:54,878 INFO    MainThread:60614 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2023-05-22 15:59:54,878 INFO    MainThread:60614 [wandb_init.py:init():535] re-initializing run, found existing run on stack: 18ttm22z
2023-05-22 15:59:54,881 INFO    MainThread:60614 [wandb_run.py:_finish():1746] finishing run test-team-12345/U-Net/18ttm22z
2023-05-22 15:59:54,881 INFO    MainThread:60614 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 0
2023-05-22 15:59:54,881 INFO    MainThread:60614 [wandb_run.py:_restore():1932] restore
2023-05-22 15:59:54,882 INFO    MainThread:60614 [wandb_run.py:_restore():1938] restore done
2023-05-22 15:59:58,747 INFO    MainThread:60614 [wandb_init.py:init():569] starting backend
2023-05-22 15:59:58,747 INFO    MainThread:60614 [wandb_init.py:init():573] setting up manager
2023-05-22 15:59:58,749 INFO    MainThread:60614 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-05-22 15:59:58,751 INFO    MainThread:60614 [wandb_init.py:init():580] backend started and connected
2023-05-22 15:59:58,755 INFO    MainThread:60614 [wandb_run.py:_label_probe_notebook():1113] probe notebook
2023-05-22 15:59:58,755 INFO    MainThread:60614 [wandb_run.py:_label_probe_notebook():1123] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-22 15:59:58,755 INFO    MainThread:60614 [wandb_init.py:init():658] updated telemetry
2023-05-22 15:59:58,755 INFO    MainThread:60614 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2023-05-22 16:00:16,694 WARNING MainThread:60614 [wandb_init.py:init():1099] interrupted
Traceback (most recent call last):
  File "/home/marco/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/marco/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 697, in init
    result = handle.wait(
  File "/home/marco/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 261, in wait
    found = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/marco/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 118, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/marco/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 114, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/marco/mambaforge/envs/deeplearning/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/home/marco/mambaforge/envs/deeplearning/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-05-22 16:00:42,829 INFO    MainThread:60614 [wandb_settings.py:_apply_login():1535] Applying login settings: {'anonymous': 'must'}
2023-05-22 16:00:42,835 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Configure stats pid to 60614
2023-05-22 16:00:42,835 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Loading settings from /home/marco/.config/wandb/settings
2023-05-22 16:00:42,835 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Loading settings from /home/marco/Documents/graph_3d_generation/wandb/settings
2023-05-22 16:00:42,835 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-05-22 16:00:42,835 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-22 16:00:42,835 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Applying login settings: {'anonymous': 'must'}
2023-05-22 16:00:42,835 INFO    MainThread:60614 [wandb_init.py:_log_setup():476] Logging user logs to /home/marco/Documents/graph_3d_generation/wandb/run-20230522_160042-por0nwr8/logs/debug.log
2023-05-22 16:00:42,835 INFO    MainThread:60614 [wandb_init.py:_log_setup():477] Logging internal logs to /home/marco/Documents/graph_3d_generation/wandb/run-20230522_160042-por0nwr8/logs/debug-internal.log
2023-05-22 16:00:42,835 INFO    MainThread:60614 [wandb_init.py:init():516] calling init triggers
2023-05-22 16:00:42,835 INFO    MainThread:60614 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2023-05-22 16:00:42,835 INFO    MainThread:60614 [wandb_init.py:init():569] starting backend
2023-05-22 16:00:42,835 INFO    MainThread:60614 [wandb_init.py:init():573] setting up manager
2023-05-22 16:00:42,837 INFO    MainThread:60614 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-05-22 16:00:42,838 INFO    MainThread:60614 [wandb_init.py:init():580] backend started and connected
2023-05-22 16:00:42,843 INFO    MainThread:60614 [wandb_run.py:_label_probe_notebook():1113] probe notebook
2023-05-22 16:00:42,843 INFO    MainThread:60614 [wandb_run.py:_label_probe_notebook():1123] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-22 16:00:42,843 INFO    MainThread:60614 [wandb_init.py:init():658] updated telemetry
2023-05-22 16:00:42,844 INFO    MainThread:60614 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2023-05-22 16:00:46,194 WARNING MainThread:60614 [wandb_init.py:init():1099] interrupted
Traceback (most recent call last):
  File "/home/marco/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/marco/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 697, in init
    result = handle.wait(
  File "/home/marco/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 261, in wait
    found = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/marco/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 118, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/marco/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 114, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/marco/mambaforge/envs/deeplearning/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/home/marco/mambaforge/envs/deeplearning/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-05-22 16:03:35,927 INFO    MainThread:60614 [wandb_settings.py:_apply_login():1535] Applying login settings: {'anonymous': 'must'}
2023-05-22 16:03:35,932 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Configure stats pid to 60614
2023-05-22 16:03:35,932 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Loading settings from /home/marco/.config/wandb/settings
2023-05-22 16:03:35,932 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Loading settings from /home/marco/Documents/graph_3d_generation/wandb/settings
2023-05-22 16:03:35,932 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-05-22 16:03:35,932 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-22 16:03:35,932 INFO    MainThread:60614 [wandb_setup.py:_flush():68] Applying login settings: {'anonymous': 'must'}
2023-05-22 16:03:35,933 INFO    MainThread:60614 [wandb_init.py:_log_setup():476] Logging user logs to /home/marco/Documents/graph_3d_generation/wandb/run-20230522_160335-j6bexncf/logs/debug.log
2023-05-22 16:03:35,933 INFO    MainThread:60614 [wandb_init.py:_log_setup():477] Logging internal logs to /home/marco/Documents/graph_3d_generation/wandb/run-20230522_160335-j6bexncf/logs/debug-internal.log
2023-05-22 16:03:35,933 INFO    MainThread:60614 [wandb_init.py:init():516] calling init triggers
2023-05-22 16:03:35,933 INFO    MainThread:60614 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2023-05-22 16:03:35,933 INFO    MainThread:60614 [wandb_init.py:init():569] starting backend
2023-05-22 16:03:35,933 INFO    MainThread:60614 [wandb_init.py:init():573] setting up manager
2023-05-22 16:03:35,935 INFO    MainThread:60614 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-05-22 16:03:35,937 INFO    MainThread:60614 [wandb_init.py:init():580] backend started and connected
2023-05-22 16:03:35,941 INFO    MainThread:60614 [wandb_run.py:_label_probe_notebook():1113] probe notebook
2023-05-22 16:03:35,942 INFO    MainThread:60614 [wandb_run.py:_label_probe_notebook():1123] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-22 16:03:35,942 INFO    MainThread:60614 [wandb_init.py:init():658] updated telemetry
2023-05-22 16:03:35,942 INFO    MainThread:60614 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2023-05-22 16:04:35,956 ERROR   MainThread:60614 [wandb_init.py:init():704] backend process timed out
2023-05-22 16:04:35,956 ERROR   MainThread:60614 [wandb_init.py:init():713] encountered error: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
